name: Run CodeBuild Action

on: push

jobs:
  codebuild-job:
    runs-on: ubuntu-latest
    name: CodeBuild Job
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@39cc6591aaf3e463bff3e3c2ea88d39184271ab5
        with:
          project-name: aws-codebuild-run-build
          hide-cloudwatch-logs: false
