name: Run CodeBuild Action

on: push

jobs:
  codebuild-job:
    runs-on: ubuntu-latest
    name: CodeBuild Job
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Run CodeBuild
        id: codebuild
        uses: taoyong-ty/aws-codebuild-run-build@0f4ef0830d01e44c988aea8bce27afc858bb2855
        with:
          project-name: aws-codebuild-run-build
          update-interval: 5
          buildspec-override:   |
            version: 0.2
            phases:
              build:
                commands:
                  - sleep 30
